In [1]:
%load_ext kedro.ipython

[01/05/25 14:19:21] INFO     Using                                                                  ]8;id=139302;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\framework\project\__init__.py\__init__.py]8;;\:]8;id=763608;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\framework\project\__init__.py#270\270]8;;\
                             'c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\framewor
                             k\project\rich_logging.yml' as logging configuration.

                    INFO     Registered line magic '%reload_kedro'                                   ]8;id=330658;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=277636;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py#61\61]8;;\

                    INFO     Registered line magic '%load_node'                                      ]8;id=995592;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=232763;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py#63\63]8;;\

                    INFO     Resolved project path as: d:\UNIWERSYTET WARSZAWSKI\Machine Learning   ]8;id=51755;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=915647;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py#178\178]8;;\
                             in Finance\II\Projects\ML_travel_insurance.
                             To set a different path, run '%reload_kedro <project_root>'

[01/05/25 14:19:23] WARNING  c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\framework ]8;id=397081;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\warnings.py\warnings.py]8;;\:]8;id=181590;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\warnings.py#112\112]8;;\
                             \project\__init__.py:347: UserWarning: The
                             'ml_travel_insurance.pipelines.data_processing' module does not expose
                             a 'create_pipeline' function, so no pipelines defined therein will be
                             returned by 'find_pipelines'.
                               warnings.warn(

                    WARNING  c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\framework ]8;id=147884;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\warnings.py\warnings.py]8;;\:]8;id=278879;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\warnings.py#112\112]8;;\
                             \project\__init__.py:347: UserWarning: The
                             'ml_travel_insurance.pipelines.data_science' module does not expose a
                             'create_pipeline' function, so no pipelines defined therein will be
                             returned by 'find_pipelines'.
                               warnings.warn(

                    INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=390025;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=64717;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro_telemetry\plugin.py#233\233]8;;\
                             the product. No personal data or IP addresses are stored on our side. If
                             you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK`
                             environment variables, or create a `.telemetry` file in the current
                             working directory with the contents `consent: false`. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

[01/05/25 14:19:24] INFO     Kedro project ML_travel_insurance                                      ]8;id=830803;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=702345;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py#144\144]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=500099;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=560110;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py#145\145]8;;\
                             'pipelines'

In [2]:
catalog.list()

[
    'travel_insurance_raw',
    'travel_insurance',
    'TI_train_raw',
    'TI_test_raw',
    'TI_y_train_raw',
    'TI_y_test_raw',
    'parameters',
    'params:model_options',
    'params:model_options.test_size',
    'params:model_options.random_state',
    'params:travel_insurance',
    'params:travel_insurance.target_col',
    'params:travel_insurance.encoding',
    'params:travel_insurance.encoding.one_hot_cols',
    'params:travel_insurance.encoding.catboost_cols'
]

In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from category_encoders.cat_boost import CatBoostEncoder

## EDA

Target label is imbalanced, hence we are using stratified train-test split.

In [4]:
%reload_kedro

X_train = catalog.load('TI_train_raw')
X_test = catalog.load('TI_test_raw')
y_train = catalog.load('TI_y_train_raw')

[01/05/25 14:19:25] INFO     Resolved project path as: D:\UNIWERSYTET WARSZAWSKI\Machine Learning   ]8;id=627255;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=322653;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py#178\178]8;;\
                             in Finance\II\Projects\ML_travel_insurance.
                             To set a different path, run '%reload_kedro <project_root>'

[01/05/25 14:19:26] WARNING  c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\framework ]8;id=3528;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\warnings.py\warnings.py]8;;\:]8;id=297085;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\warnings.py#112\112]8;;\
                             \project\__init__.py:347: UserWarning: The
                             'ml_travel_insurance.pipelines.data_processing' module does not expose
                             a 'create_pipeline' function, so no pipelines defined therein will be
                             returned by 'find_pipelines'.
                               warnings.warn(

                    WARNING  c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\framework ]8;id=983806;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\warnings.py\warnings.py]8;;\:]8;id=11015;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\warnings.py#112\112]8;;\
                             \project\__init__.py:347: UserWarning: The
                             'ml_travel_insurance.pipelines.data_science' module does not expose a
                             'create_pipeline' function, so no pipelines defined therein will be
                             returned by 'find_pipelines'.
                               warnings.warn(

                    INFO     Kedro is sending anonymous usage data with the sole purpose of improving ]8;id=538014;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro_telemetry\plugin.py\plugin.py]8;;\:]8;id=15009;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro_telemetry\plugin.py#233\233]8;;\
                             the product. No personal data or IP addresses are stored on our side. If
                             you want to opt out, set the `KEDRO_DISABLE_TELEMETRY` or `DO_NOT_TRACK`
                             environment variables, or create a `.telemetry` file in the current
                             working directory with the contents `consent: false`. Read more at
                             https://docs.kedro.org/en/stable/configuration/telemetry.html

                    INFO     Kedro project ML_travel_insurance                                      ]8;id=239519;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=61442;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py#144\144]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=638664;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py\__init__.py]8;;\:]8;id=387068;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\ipython\__init__.py#145\145]8;;\
                             'pipelines'

                    INFO     Loading data from TI_train_raw (CSVDataset)...                     ]8;id=888711;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=274947;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py#389\389]8;;\

                    INFO     Loading data from TI_test_raw (CSVDataset)...                      ]8;id=432453;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=895084;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py#389\389]8;;\

                    INFO     Loading data from TI_y_train_raw (CSVDataset)...                   ]8;id=913375;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=168889;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py#389\389]8;;\

In [5]:
X_train.head(10)

,agency,agency_type,distribution_channel,product_name,duration,destination,net_sales,commision,gender,age
0,EPX,Travel Agency,Online,Cancellation Plan,18,PHILIPPINES,13.0,0.00,NaN,36
1,EPX,Travel Agency,Online,Cancellation Plan,101,THAILAND,20.0,0.00,NaN,30
2,EPX,Travel Agency,Online,2 way Comprehensive Plan,25,"KOREA, REPUBLIC OF",66.0,0.00,NaN,36
3,EPX,Travel Agency,Online,2 way Comprehensive Plan,50,CHINA,44.0,0.00,NaN,36
4,C2B,Airlines,Online,Bronze Plan,21,SINGAPORE,33.5,8.38,F,22
5,RAB,Airlines,Online,Value Plan,6,BRUNEI DARUSSALAM,15.0,6.00,M,47
6,EPX,Travel Agency,Online,2 way Comprehensive Plan,103,THAILAND,20.0,0.00,NaN,30
7,JZI,Airlines,Online,Basic Plan,8,MYANMAR,18.0,6.30,F,32
8,KML,Travel Agency,Online,Value Plan,128,FRANCE,109.0,41.42,M,48
9,C2B,Airlines,Online,Bronze Plan,17,SINGAPORE,20.0,5.00,F,21

### Missing Values

In [6]:
print('Train size:', X_train.shape[0])

Train size: 50660

In [7]:
X_train.isna().sum()

agency                      0
agency_type                 0
distribution_channel        0
product_name                0
duration                    0
destination                 0
net_sales                   0
commision                   0
gender                  36124
age                         0
dtype: int64

In [8]:
X_test.isna().sum()

agency                     0
agency_type                0
distribution_channel       0
product_name               0
duration                   0
destination                0
net_sales                  0
commision                  0
gender                  8983
age                        0
dtype: int64

Only gender has missing values. We will create new category 'Missing' for them.

In [9]:
X_train.loc[X_train['gender'].isna(), 'gender'] = 'Missing'
X_train['gender']

0        Missing
1        Missing
2        Missing
3        Missing
4              F
          ...
50655    Missing
50656    Missing
50657          M
50658    Missing
50659    Missing
Name: gender, Length: 50660, dtype: object

### Columns

#### Agency

Use catboost encoding.

In [10]:
agency_names = np.unique(np.concatenate([X_train['agency'], X_test['agency']]))
agency_names

array(['ADM', 'ART', 'C2B', 'CBH', 'CCR', 'CSR', 'CWT', 'EPX', 'JWT',
       'JZI', 'KML', 'LWC', 'RAB', 'SSI', 'TST', 'TTW'], dtype=object)

#### Agency Type

Use one-hot encoding.

In [11]:
agency_types = np.unique(
    np.concatenate([X_train['agency_type'], X_test['agency_type']])
)
agency_types

array(['Airlines', 'Travel Agency'], dtype=object)

#### Distribution Channel

Use one-hot encoding.

In [12]:
distr_types = np.unique(
    np.concatenate([X_train['distribution_channel'], X_test['distribution_channel']])
)
distr_types

array(['Offline', 'Online'], dtype=object)

#### Product Name

Use catboost encoding.

In [13]:
product_names = np.unique(
    np.concatenate([X_train['product_name'], X_test['product_name']])
)
product_names

array(['1 way Comprehensive Plan', '2 way Comprehensive Plan',
       '24 Protect', 'Annual Gold Plan', 'Annual Silver Plan',
       'Annual Travel Protect Gold', 'Annual Travel Protect Platinum',
       'Annual Travel Protect Silver', 'Basic Plan', 'Bronze Plan',
       'Cancellation Plan', 'Child Comprehensive Plan',
       'Comprehensive Plan', 'Gold Plan', 'Individual Comprehensive Plan',
       'Premier Plan', 'Rental Vehicle Excess Insurance', 'Silver Plan',
       'Single Trip Travel Protect Gold',
       'Single Trip Travel Protect Platinum',
       'Single Trip Travel Protect Silver',
       'Spouse or Parents Comprehensive Plan', 'Ticket Protector',
       'Travel Cruise Protect', 'Travel Cruise Protect Family',
       'Value Plan'], dtype=object)

### Categorical Encoding

In [14]:
oh_cols = catalog.load('params:travel_insurance.encoding.one_hot_cols')

X_train = pd.get_dummies(X_train, columns=oh_cols)

                    INFO     Loading data from params:travel_insurance.encoding.one_hot_cols    ]8;id=272704;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=337226;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py#389\389]8;;\
                             (MemoryDataset)...

In [38]:
catboost_cols = catalog.load('params:travel_insurance.encoding.catboost_cols')

CBE_encoder = CatBoostEncoder(cols=catboost_cols)
train_cbe = CBE_encoder.fit_transform(X_train.sort_values(by='net_sales'), y_train)
train_cbe.head(10)

[01/05/25 14:32:53] INFO     Loading data from params:travel_insurance.encoding.catboost_cols   ]8;id=153292;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py\data_catalog.py]8;;\:]8;id=928;file://c:\Users\shele\miniforge3\envs\ML_II\Lib\site-packages\kedro\io\data_catalog.py#389\389]8;;\
                             (MemoryDataset)...

,agency,product_name,duration,destination,net_sales,commision,age,agency_type_Airlines,agency_type_Travel Agency,distribution_channel_Offline,distribution_channel_Online,gender_F,gender_M,gender_Missing
16946,0.014647,0.014647,364,0.014647,-389.00,97.25,27,True,False,False,True,False,True,False
25041,0.007323,0.014647,176,0.007323,-357.50,89.38,24,True,False,False,True,False,True,False
41603,0.014647,0.014647,65,0.014647,-297.00,178.20,34,False,True,False,True,False,False,True
28543,0.004882,0.007323,389,0.004882,-291.75,72.94,29,True,False,False,True,True,False,False
12255,0.003662,0.004882,390,0.003662,-291.75,72.94,29,True,False,False,True,True,False,False
7611,0.002929,0.003662,365,0.002929,-289.00,72.25,30,True,False,False,True,False,True,False
23555,0.002441,0.014647,366,0.002441,-287.40,71.85,65,True,False,False,True,True,False,False
19956,0.007323,0.007323,52,0.014647,-287.10,172.26,31,False,True,False,True,False,False,True
9098,0.002092,0.014647,158,0.002092,-281.00,70.25,22,True,False,False,True,True,False,False
38867,0.004882,0.004882,193,0.014647,-277.20,166.32,65,False,True,False,True,False,False,True

In [34]:
y_train

      claim
0        No
1        No
2        No
3        No
4        No
...     ...
50655    No
50656    No
50657    No
50658    No
50659    No

[50660 rows x 1 columns]